### ISSUE TITLE
3 or more items have strange message format

### ISSUE THREAD

**Issue by fbegyn** [ZeusWPI/Tap#131]
When you order 3 or more items the message entry that gets send to tab ends up like this `1 Ice Tea 33 cl, 1 Kinder Bueno, and 1 Lay's Oven Baked Mediterrean Herbs`.

The `, and` should be fixed and I propose to get rid of the `,` because it breaks my export to csv for hledger :stuck_out_tongue:

**Comment by wschella** [comment]
Boooh, oxford commas ftw!

**Comment by fbegyn** [comment]
If I'm the only one disagreeing with the Oxford comma I can live with it, was just something I noticed. IMHO there's no possible way to misinterpret the sentence here as what the Oxford comma tries to prevent.

**Comment by TomNaessens** [comment]
@fbegyn This does not sound like an issue with the message format, but with the exporter. Any product with a comma in its name would cause this. Which csv exporter is this?

**Comment by fbegyn** [comment]
One that I no longer use, so this issue can be closed
