### ISSUE TITLE
Order users by frecency

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/Tap#94]

**Comment by NoctuaNivalis** [comment]
I'm not sure this would be useful. Without this, people may have to scroll a lot to find their button, but at least the button will be always at the same place. When users are ordered by frequency, they'll swap around a lot.

Note that the swapping may lessen after some time.

**Comment by iasoon** [comment]
I don't think that is a valid concern, as the buttons are very easily recognisable due to your avatar.

**Comment by Procrat** [comment]
NoctuaNivalis: I think this will quickly converge to a semi-consistent place for every avatar, NoctuaNivalis.

**Comment by Procrat** [comment]
Why is this closed?

**Comment by iasoon** [comment]
Because we fixed it!!!1!

**Comment by Procrat** [comment]
zOMG, your teh best, @iasoon!!shift1 xoxox
