### ISSUE TITLE
Ordering dagschotels in own browser

### ISSUE THREAD

**Issue by NoctuaNivalis** [ZeusWPI/Tap#95]
Ordering dagschotels from your own browser is hard. Perhaps adding a button next to the "Place new order" saying "Order dagschotel" would be nice?

**Comment by tl3ilaxu** [comment]
Maybe just make the dagschotel image clickable and make that the dagschotel order button ?

**Comment by becousae** [comment]
Is this gonna be clear? 

That part of the sidebar is meant to edit your settings. I would suspect clicking the image to bring you to a page to change your dagschotel

**Comment by tl3ilaxu** [comment]
Perhaps move the dagschotel image to the "orders" portion of the side bar? That way it's clear what the current dagschotel is and dagschotel ordering is consistent with koelkast. Might need a label for clarity.

**Comment by redfast00** [comment]
This is possible.
